FROM node:16-alpine

# Install ngrok
RUN apk add --no-cache wget && \
    wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && \
    unzip ngrok-stable-linux-amd64.zip && \
    rm ngrok-stable-linux-amd64.zip && \
    mv ngrok /usr/local/bin/ngrok && \
    apk del wget


# Install curl and jq
RUN apk add --no-cache curl jq

# Set working directory
WORKDIR /app

# Copy app files
COPY package.json ./package.json
COPY DFFullfillment.js ./DFFullfillment.js
COPY serviceAccountKey.json ./serviceAccountKey.json
COPY makePortOnline.sh ./makePortOnline.sh

# Install dependencies
RUN npm install

# Expose port
EXPOSE 3030

# Start ngrok and update fulfillment URL
CMD ["sh", "-c", "./makePortOnline.sh"]