FROM node:16-alpine

WORKDIR /app

COPY pages pages
COPY public public
COPY redux redux
COPY styles styles

COPY next-env.d.ts next-env.d.ts
COPY next.config.js next.config.js
COPY package-lock.json package-lock.json
COPY package.json package.json
COPY tailwind.config.js tailwind.config.js
COPY postcss.config.js postcss.config.js
COPY tsconfig.json tsconfig.json

RUN npm install

CMD ["npm", "run", "dev"]

EXPOSE 3000
